/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package userInteface;

import business.PersonDirectory;
import java.awt.CardLayout;
import userInteface.Patient.ManagePatientsJPanel;
import userInteface.Patient.ManageVitalSignsJPanel;
import userInteface.Person.ManagePersonsJPanel;


public class MainJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainJFrame
     */
    private PersonDirectory personDirectory;
    public MainJFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        personDirectory= new PersonDirectory();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        patientManagerJButton = new javax.swing.JButton();
        managePersonsJButton = new javax.swing.JButton();
        patientManagerJButton1 = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));

        jSplitPane1.setMinimumSize(new java.awt.Dimension(700, 700));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(700, 700));

        leftJPanel.setBackground(new java.awt.Color(204, 204, 255));
        leftJPanel.setMinimumSize(new java.awt.Dimension(200, 700));
        leftJPanel.setPreferredSize(new java.awt.Dimension(200, 700));

        patientManagerJButton.setBackground(new java.awt.Color(102, 0, 102));
        patientManagerJButton.setForeground(new java.awt.Color(255, 255, 255));
        patientManagerJButton.setText("Manage Patients");
        patientManagerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientManagerJButtonActionPerformed(evt);
            }
        });

        managePersonsJButton.setBackground(new java.awt.Color(102, 0, 102));
        managePersonsJButton.setForeground(new java.awt.Color(255, 255, 255));
        managePersonsJButton.setText("Manage People");
        managePersonsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonsJButtonActionPerformed(evt);
            }
        });

        patientManagerJButton1.setBackground(new java.awt.Color(102, 0, 102));
        patientManagerJButton1.setForeground(new java.awt.Color(255, 255, 255));
        patientManagerJButton1.setText("Manage Vital Signs");
        patientManagerJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientManagerJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientManagerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managePersonsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientManagerJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(managePersonsJButton)
                .addGap(76, 76, 76)
                .addComponent(patientManagerJButton)
                .addGap(79, 79, 79)
                .addComponent(patientManagerJButton1)
                .addGap(283, 283, 283))
        );

        jSplitPane1.setLeftComponent(leftJPanel);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 255));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(500, 700));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(500, 700));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientManagerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientManagerJButtonActionPerformed
        // TODO add your handling code here:
        /*PatientManagerWorkAreaJPanel pmwaJPanel=
                new PatientManagerWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("pmwaJPanel", pmwaJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
        ManagePatientsJPanel mpJPanel= 
                new ManagePatientsJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("mpJPanel", mpJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_patientManagerJButtonActionPerformed

    private void managePersonsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePersonsJPanel mpJPanel= 
                new ManagePersonsJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("mpJPanel", mpJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonsJButtonActionPerformed

    private void patientManagerJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientManagerJButton1ActionPerformed
        // TODO add your handling code here:
        ManageVitalSignsJPanel mvsJPanel= 
                new ManageVitalSignsJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("mvsJPanel", mvsJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_patientManagerJButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton managePersonsJButton;
    private javax.swing.JButton patientManagerJButton;
    private javax.swing.JButton patientManagerJButton1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
